### job 配置项
jobs:
  java-sec:
    image: registry.erda.cloud/erda-actions/java-dependency-check-action:1.0-20221114110332-8501675
    resources:
      cpu: 1
      mem: 4096
    binds:
      # maven 依赖缓存
      - ((storageMountPoint))/devops/actions/java-dependency-check/maven-cache/.m2:/root/.m2
