### job 配置项
jobs:
  agent:
    image: registry.erda.cloud/erda-actions/action-agent:2.4-alpha-20231124102514-fd60919fc
    labels:
      # 必填字段
      MD5: fbf7436210dc875b1050c6ed1da09ce7
    envs:
      # DEBUG mode, will produce more logs
      DEBUG: false
      # push log to collector
      ENABLE_PUSH_LOG_TO_COLLECTOR: false
      STDERR_REGEXP_LIST: '["^[a-z]*can*","^[a-z]*fail*"]'
      ENCRYPTED_VAlUE_MIN_LEN: 6
      FILE_STREAM_TIMEOUT_SEC: 60
      DEFAULT_SHELL: sh -x -e
      DEFAULT_TIMEZONE: Asia/Shanghai
      MAX_CACHE_FILE_MB: 2048
